# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: setup
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: build
        run: go build -v ./...

      - name: test
        run: go test -v ./...

      - name: gofmt
        if: matrix.os == 'ubuntu-latest'
        run: exit $(gofmt -l . | wc -l)

      - name: vet
        if: matrix.os == 'ubuntu-latest'
        run: go vet -all=true -v=true .
